#!/bin/bash

set -e

# The parameter $1 is the backup directory location dedicated to the app
BACKUP_DIR=$1

# The parameter $2 is theid of the app instance ex: strut__2
APP=$2

domain=$(sudo yunohost app setting $APP domain)

# Copy the app files
final_path=/opt/$APP
sudo cp -a $final_path "${BACKUP_DIR}/www"

# Copy the conf files
sudo mkdir -p "${BACKUP_DIR}/conf"
sudo cp -a /etc/nginx/conf.d/$domain.d/$APP.conf "${BACKUP_DIR}/conf/nginx.conf"

# Backup data
repo_path=$(sudo yunohost app setting $APP repopath)
sudo mkdir -p "${BACKUP_DIR}/data"
sudo cp -a $repo_path/. "${BACKUP_DIR}/data"

# Backup mysql
db_pwd=$(sudo yunohost app setting $APP mysqlpwd)
sudo mysqldump -u $APP -p$db_pwd $APP > "${BACKUP_DIR}/$APP.dmp"