#!/bin/bash
app=gogs

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
mkdir -p $backup_dir

# Backup data
repo_path=$(sudo yunohost app setting $app repopath)
mkdir -p $backup_dir/data
sudo cp -a $repo_path/. $backup_dir/data

# Backup config
mkdir -p $backup_dir/conf
cp /opt/gogs/custom/conf/app.ini $backup_dir/conf/app.ini

# Backup mysql
db_pwd=$(sudo yunohost app setting $app mysqlpwd)
sudo mysqldump -u $app -p$db_pwd $app > $backup_dir/$app.dmp

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
domain=$(sudo yunohost app setting $app domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf