#!/bin/bash
app=gogs

# Retrieve settings
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
repo_path=$(sudo yunohost app setting $app repopath)
db_pwd=$(sudo yunohost app setting $app mysqlpwd)
key=$(sudo yunohost app setting $app secret_key)
adminusername=$(sudo yunohost app setting $app adminusername)

# cut the second "/" of path
path="/$(echo "$path" | cut -d/ -f2)"

# Stop service
sudo service gogs stop

final_path=/opt/$app

# Build Gogs
sudo rm -rf "$final_path"_src
base_directory=$PWD
export GOPATH="$final_path"_src
tar xzf ../sources/gogs_src.tar.gz
sudo mv gogs_src $GOPATH
cd $GOPATH/src/github.com/gogits/gogs
sudo GOPATH="$final_path"_src: go get ./...
sudo GOPATH="$final_path"_src: go build
cd $base_directory

# Create a link to static files
sudo rm -rf $final_path/log
sudo rm -rf $final_path/custom
sudo rm -rf $final_path/data
sudo ln -fs /etc/gogs $final_path/custom
sudo ln -fs /home/gogs/data $final_path/data
sudo ln -fs /var/log/gogs $final_path/log

# Configure init script
if [[ $(cat /etc/debian_version) = "7."* ]]
then
    sudo cp ../conf/sysvinit/gogs /etc/init.d/
    sudo chmod u+x /etc/init.d/gogs
    sudo update-rc.d gogs defaults
else
    sudo cp ../conf/systemd/gogs.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable gogs.service
fi

# Configure logrotate
sudo cp ../conf/logrotate /etc/logrotate.d/gogs
sudo service rsyslog restart

# ensure directory for custom config is present
sudo mkdir -p /opt/gogs/custom/conf/

# Set gogs user for gogs directory
sudo chown gogs:gogs -R  "$final_path"_src
sudo chown gogs:gogs -R $final_path
sudo chown -hR gogs:gogs $repo_path
sudo chown -R gogs:gogs /var/log/gogs
sudo chown -R gogs:gogs /home/gogs

# Copy and edit app.ini
sudo cp ../conf/app.ini $final_path/custom/conf
sudo sed -i "s@yuno_repo@$repo_path@g" $final_path/custom/conf/app.ini
sudo sed -i "s@yuno_url@$domain$path@g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_dbpdw/$db_pwd/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_dbuser/$app/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_domain/$domain/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_key/$key/g" $final_path/custom/conf/app.ini
sudo chown gogs:gogs $final_path/custom/conf/app.ini

# Restore ldap config
sudo sed -i "s@yuno_admin@a$dminusername@g" ../conf/login_source.sql
mysql -u root -p$(sudo cat /etc/yunohost/mysql)  < ../conf/login_source.sql

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@${path%/}@g" ../conf/nginx.conf
if [ "$path" = "/" ]
then
    sed -i "s@COMMENT_IF_ROOT@#@g" ../conf/nginx.conf
else
    sed -i "s@COMMENT_IF_ROOT@@g" ../conf/nginx.conf
fi
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

sudo service gogs start

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf